services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword # Set a root password
      MYSQL_DATABASE: ecommdb
      MYSQL_USER: raj
      MYSQL_PASSWORD: raj123
    healthcheck:
      # This command checks if MySQL is actually ready for connections
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend # Path to your FastAPI folder
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env.docker
    environment:
      - DB_HOST=db  # Overrides localhost to use the internal 'db' container name
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend/app/media:/app/app/media

  frontend:
    build:
      context: ./frontend # Path to your Next.js folder
      args:
        NEXT_PUBLIC_API_BASE_URL: "http://localhost:8000"
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mysql_data:
